// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using arBrain.Data;

#nullable disable

namespace arBrain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("arBrain.Models.Cerveja", b =>
                {
                    b.Property<int>("CervejaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cerveja_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CervejaId"));

                    b.Property<int>("CervejaEstiloId")
                        .HasColumnType("integer")
                        .HasColumnName("cerveja_estilo_id");

                    b.Property<DateTime?>("CervejaExclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cerveja_exclusao");

                    b.Property<DateTime>("CervejaInclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cerveja_inclusao");

                    b.Property<string>("CervejaNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cerveja_nome");

                    b.Property<string>("CervejaObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cerveja_observacao");

                    b.HasKey("CervejaId")
                        .HasName("pk_cervejas");

                    b.HasIndex("CervejaEstiloId")
                        .HasDatabaseName("ix_cervejas_cerveja_estilo_id");

                    b.ToTable("cervejas", (string)null);
                });

            modelBuilder.Entity("arBrain.Models.CervejaEstilo", b =>
                {
                    b.Property<int>("CervejaEstiloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cerveja_estilo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CervejaEstiloId"));

                    b.Property<string>("CervejaEstiloDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cerveja_estilo_descricao");

                    b.Property<DateTime?>("CervejaEstiloExclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cerveja_estilo_exclusao");

                    b.Property<DateTime>("CervejaEstiloInclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cerveja_estilo_inclusao");

                    b.Property<string>("CervejaEstiloObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cerveja_estilo_observacao");

                    b.HasKey("CervejaEstiloId")
                        .HasName("pk_cerveja_estilos");

                    b.ToTable("cerveja_estilos", (string)null);
                });

            modelBuilder.Entity("arBrain.Models.CervejaParametros.CervejaParametro", b =>
                {
                    b.Property<int>("CervejaParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cerveja_parametro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CervejaParametroId"));

                    b.Property<int>("CervejaId")
                        .HasColumnType("integer")
                        .HasColumnName("cerveja_id");

                    b.Property<DateTime?>("CervejaParametroExclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cerveja_parametro_exclusao");

                    b.Property<decimal>("CervejaParametroExtratoMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cerveja_parametro_extrato_max");

                    b.Property<decimal>("CervejaParametroExtratoMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cerveja_parametro_extrato_min");

                    b.Property<DateTime>("CervejaParametroInclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cerveja_parametro_inclusao");

                    b.Property<string>("CervejaParametroObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cerveja_parametro_observacao");

                    b.Property<decimal>("CervejaParametroPhMax")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cerveja_parametro_ph_max");

                    b.Property<decimal>("CervejaParametroPhMin")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("cerveja_parametro_ph_min");

                    b.Property<decimal>("CervejaParametroTemperaturaMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cerveja_parametro_temperatura_max");

                    b.Property<decimal>("CervejaParametroTemperaturaMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cerveja_parametro_temperatura_min");

                    b.HasKey("CervejaParametroId")
                        .HasName("pk_cerveja_parametros");

                    b.HasIndex("CervejaId")
                        .HasDatabaseName("ix_cerveja_parametros_cerveja_id");

                    b.ToTable("cerveja_parametros", (string)null);
                });

            modelBuilder.Entity("arBrain.Models.FermentacaoHistorico.FermentacaoHistorico", b =>
                {
                    b.Property<int>("HistoricoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("historico_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoricoId"));

                    b.Property<DateTime>("HistoricoDataColeta")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("historico_data_coleta");

                    b.Property<decimal>("HistoricoExtrato")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("historico_extrato");

                    b.Property<string>("HistoricoObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("historico_observacao");

                    b.Property<decimal>("HistoricoPh")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("historico_ph");

                    b.Property<string>("HistoricoResponsavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("historico_responsavel");

                    b.Property<decimal>("HistoricoTemperatura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("historico_temperatura");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_id");

                    b.HasKey("HistoricoId")
                        .HasName("pk_fermentacao_historicos");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_fermentacao_historicos_lote_id");

                    b.ToTable("fermentacao_historicos", (string)null);
                });

            modelBuilder.Entity("arBrain.Models.Lote.Lote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lote_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoteId"));

                    b.Property<int>("CervejaId")
                        .HasColumnType("integer")
                        .HasColumnName("cerveja_id");

                    b.Property<string>("LoteDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lote_descricao");

                    b.Property<DateTime?>("LoteExclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lote_exclusao");

                    b.Property<DateTime?>("LoteFinalizacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lote_finalizacao");

                    b.Property<DateTime>("LoteInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lote_inicio");

                    b.Property<string>("LoteObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("lote_observacao");

                    b.Property<decimal>("LoteQuantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("lote_quantidade");

                    b.Property<int>("TanqueId")
                        .HasColumnType("integer")
                        .HasColumnName("tanque_id");

                    b.HasKey("LoteId")
                        .HasName("pk_lotes");

                    b.HasIndex("CervejaId")
                        .HasDatabaseName("ix_lotes_cerveja_id");

                    b.HasIndex("TanqueId")
                        .HasDatabaseName("ix_lotes_tanque_id");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("arBrain.Models.Tanque.Tanque", b =>
                {
                    b.Property<int>("TanqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tanque_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TanqueId"));

                    b.Property<decimal>("TanqueCapacidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("tanque_capacidade");

                    b.Property<string>("TanqueDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tanque_descricao");

                    b.Property<DateTime?>("TanqueExclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tanque_exclusao");

                    b.Property<DateTime>("TanqueInclusao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tanque_inclusao");

                    b.Property<string>("TanqueObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("tanque_observacao");

                    b.HasKey("TanqueId")
                        .HasName("pk_tanques");

                    b.ToTable("tanques", (string)null);
                });

            modelBuilder.Entity("arBrain.Models.Cerveja", b =>
                {
                    b.HasOne("arBrain.Models.CervejaEstilo", "CervejaEstilo")
                        .WithMany("Cervejas")
                        .HasForeignKey("CervejaEstiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cervejas_cerveja_estilos_cerveja_estilo_id");

                    b.Navigation("CervejaEstilo");
                });

            modelBuilder.Entity("arBrain.Models.CervejaParametros.CervejaParametro", b =>
                {
                    b.HasOne("arBrain.Models.Cerveja", "Cerveja")
                        .WithMany()
                        .HasForeignKey("CervejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cerveja_parametros_cervejas_cerveja_id");

                    b.Navigation("Cerveja");
                });

            modelBuilder.Entity("arBrain.Models.FermentacaoHistorico.FermentacaoHistorico", b =>
                {
                    b.HasOne("arBrain.Models.Lote.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fermentacao_historicos_lotes_lote_id");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("arBrain.Models.Lote.Lote", b =>
                {
                    b.HasOne("arBrain.Models.Cerveja", "Cerveja")
                        .WithMany("Lotes")
                        .HasForeignKey("CervejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_cervejas_cerveja_id");

                    b.HasOne("arBrain.Models.Tanque.Tanque", "Tanque")
                        .WithMany("Lotes")
                        .HasForeignKey("TanqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_tanques_tanque_id");

                    b.Navigation("Cerveja");

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("arBrain.Models.Cerveja", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("arBrain.Models.CervejaEstilo", b =>
                {
                    b.Navigation("Cervejas");
                });

            modelBuilder.Entity("arBrain.Models.Tanque.Tanque", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
