// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using arBrain.Data;

#nullable disable

namespace arBrain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("arBrain.Models.Cerveja", b =>
                {
                    b.Property<int>("CervejaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CervejaId"));

                    b.Property<int>("CervejaEstiloId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CervejaExclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CervejaInclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CervejaNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CervejaObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("CervejaId");

                    b.HasIndex("CervejaEstiloId");

                    b.ToTable("Cervejas");
                });

            modelBuilder.Entity("arBrain.Models.CervejaEstilo", b =>
                {
                    b.Property<int>("CervejaEstiloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CervejaEstiloId"));

                    b.Property<string>("CervejaEstiloDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CervejaEstiloExclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CervejaEstiloInclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CervejaEstiloObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("CervejaEstiloId");

                    b.ToTable("CervejaEstilos");
                });

            modelBuilder.Entity("arBrain.Models.CervejaParametros.CervejaParametro", b =>
                {
                    b.Property<int>("CervejaParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CervejaParametroId"));

                    b.Property<int>("CervejaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CervejaParametroExclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CervejaParametroExtratoMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("CervejaParametroExtratoMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CervejaParametroInclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CervejaParametroObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("CervejaParametroPhMax")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<decimal>("CervejaParametroPhMin")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<decimal>("CervejaParametroTemperaturaMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("CervejaParametroTemperaturaMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("CervejaParametroId");

                    b.HasIndex("CervejaId");

                    b.ToTable("CervejaParametros");
                });

            modelBuilder.Entity("arBrain.Models.FermentacaoHistorico.FermentacaoHistorico", b =>
                {
                    b.Property<int>("HistoricoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoricoId"));

                    b.Property<DateTime>("HistoricoDataColeta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("HistoricoExtrato")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("HistoricoObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("HistoricoPh")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)");

                    b.Property<string>("HistoricoResponsavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("HistoricoTemperatura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.HasKey("HistoricoId");

                    b.HasIndex("LoteId");

                    b.ToTable("FermentacaoHistoricos");
                });

            modelBuilder.Entity("arBrain.Models.Lote.Lote", b =>
                {
                    b.Property<int>("LoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoteId"));

                    b.Property<int>("CervejaId")
                        .HasColumnType("integer");

                    b.Property<string>("LoteDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LoteExclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LoteFinalizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LoteInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LoteObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("LoteQuantidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TanqueId")
                        .HasColumnType("integer");

                    b.HasKey("LoteId");

                    b.HasIndex("CervejaId");

                    b.HasIndex("TanqueId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("arBrain.Models.Tanque.Tanque", b =>
                {
                    b.Property<int>("TanqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TanqueId"));

                    b.Property<decimal>("TanqueCapacidade")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TanqueDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("TanqueExclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TanqueInclusao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TanqueObservacao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("TanqueId");

                    b.ToTable("Tanques");
                });

            modelBuilder.Entity("arBrain.Models.Cerveja", b =>
                {
                    b.HasOne("arBrain.Models.CervejaEstilo", "CervejaEstilo")
                        .WithMany("Cervejas")
                        .HasForeignKey("CervejaEstiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CervejaEstilo");
                });

            modelBuilder.Entity("arBrain.Models.CervejaParametros.CervejaParametro", b =>
                {
                    b.HasOne("arBrain.Models.Cerveja", "Cerveja")
                        .WithMany()
                        .HasForeignKey("CervejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cerveja");
                });

            modelBuilder.Entity("arBrain.Models.FermentacaoHistorico.FermentacaoHistorico", b =>
                {
                    b.HasOne("arBrain.Models.Lote.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("arBrain.Models.Lote.Lote", b =>
                {
                    b.HasOne("arBrain.Models.Cerveja", "Cerveja")
                        .WithMany("Lotes")
                        .HasForeignKey("CervejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("arBrain.Models.Tanque.Tanque", "Tanque")
                        .WithMany("Lotes")
                        .HasForeignKey("TanqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cerveja");

                    b.Navigation("Tanque");
                });

            modelBuilder.Entity("arBrain.Models.Cerveja", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("arBrain.Models.CervejaEstilo", b =>
                {
                    b.Navigation("Cervejas");
                });

            modelBuilder.Entity("arBrain.Models.Tanque.Tanque", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
